[package]
name = "poem-hypertext"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.31"
hypertext = { version = "0.5.1" }
poem = { version = "3.1.3", features = ["session", "static-files", "sse"] }
tokio = { version = "1.41.0", features = ["full"] }
tokio-stream = "0.1.16"
